# Generated by Django 3.2.12 on 2025-02-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('top_up', 'Top-Up'), ('purchase', 'Purchase'), ('refund', 'Refund')], max_length=20),
        ),
    ]
