# Generated by Django 4.2.9 on 2025-02-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('store', 'Store'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
