# Generated by Django 4.2.9 on 2025-03-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_topup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
